// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHbRVtWkXftRYm8SVhzMDgjV5QWTxcvGo',
    appId: '1:51947426164:web:89f687d8bf3b96f5461c21',
    messagingSenderId: '51947426164',
    projectId: 'innova-hub-239af',
    authDomain: 'innova-hub-239af.firebaseapp.com',
    storageBucket: 'innova-hub-239af.firebasestorage.app',
    measurementId: 'G-YLMQDCZYDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCqt6uirlqByxinR3hlCHaJquihwS2s-Q',
    appId: '1:51947426164:android:3e31a80251b67e0b461c21',
    messagingSenderId: '51947426164',
    projectId: 'innova-hub-239af',
    storageBucket: 'innova-hub-239af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwCTFXYlOnthOgCdWOa1bg4FJvv0vha5k',
    appId: '1:51947426164:ios:732c434ff2f67026461c21',
    messagingSenderId: '51947426164',
    projectId: 'innova-hub-239af',
    storageBucket: 'innova-hub-239af.firebasestorage.app',
    iosBundleId: 'com.example.innovahubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwCTFXYlOnthOgCdWOa1bg4FJvv0vha5k',
    appId: '1:51947426164:ios:732c434ff2f67026461c21',
    messagingSenderId: '51947426164',
    projectId: 'innova-hub-239af',
    storageBucket: 'innova-hub-239af.firebasestorage.app',
    iosBundleId: 'com.example.innovahubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHbRVtWkXftRYm8SVhzMDgjV5QWTxcvGo',
    appId: '1:51947426164:web:2024ad3415187ad2461c21',
    messagingSenderId: '51947426164',
    projectId: 'innova-hub-239af',
    authDomain: 'innova-hub-239af.firebaseapp.com',
    storageBucket: 'innova-hub-239af.firebasestorage.app',
    measurementId: 'G-WQMMPFT667',
  );
}
